// <auto-generated />
namespace gamejamtarts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixingCreationDateToBeADate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingCreationDateToBeADate));
        
        string IMigrationMetadata.Id
        {
            get { return "201208270433390_FixingCreationDateToBeADate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
