// <auto-generated />
namespace gamejamtarts.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RefactorGameStructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefactorGameStructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201208161008315_RefactorGameStructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
